benefits/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('customers.urls')),
    path('partner/', include('partners.urls')),
    path('account/', include('members.urls')),
    path('perks/', include('perks.urls')),
    path('', include('cms.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = settings.ADMIN_SITE_HEADER

cms/urls.py
from django.conf.urls import url

from . import views

app_name = 'cms'

urlpatterns = [
    url(r'^$', views.index.as_view(), name='index'),
]

partners/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'partners'

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^my_perks/', views.my_perks, name='my_perks'),
    url(r'^sign_in/', views.sign_in, name='sign_in'),
    url(r'^logout/', auth_views.LogoutView.as_view(),
        {'next_page': '/partner/'}, name='logout'),
    url(r'^change_password/', views.change_password, name='change_password'),
]

partners/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings


class Partner(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                verbose_name='Учетная запись')
    name = models.CharField(max_length=100,
                            verbose_name='Наименование Компании')
    info = models.TextField(verbose_name='Контактная информация',
                            null=True, blank=True)

    class Meta:
        verbose_name = 'Партнер'
        verbose_name_plural = 'Партнеры'

    def __str__(self):
        return self.name

partners/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth import authenticate
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit


class SigninForm(forms.Form):
    email = forms.EmailField(label='Email')
    password = forms.CharField(label='Пароль',
                               max_length=32, widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(SigninForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_show_labels = False
        self.helper.add_input(Submit('submit', 'Войти',
                                     css_class='btn btn-block'))
        layout = self.helper.layout = Layout()
        for field_name, field in self.fields.items():
            layout.append(Field(field_name, placeholder=field.label))

    def clean(self):
        cleaned_data = super(SigninForm, self).clean()
        email = cleaned_data['email']
        password = cleaned_data['password']
        user_cache = authenticate(username=email, password=password)
        if user_cache is None:
            raise forms.ValidationError('Вы ввели неверный e-mail или пароль')
        if not user_cache.is_partner:
            raise forms.ValidationError('У вашей учетной записи недостаточно прав \
                                  для просмотра данной страницы')

partners/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from .forms import SigninForm
from perks.models import Perk, Transaction


def is_partner(user):
    if user.is_anonymous:
        return False
    else:
        return user.is_partner


def sign_in(request):
    if request.user.is_authenticated and request.user.is_partner:
        return redirect('partners:dashboard')
    next_page = request.GET.get('next')
    if request.method == 'POST':
        form = SigninForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, username=email, password=password)
            login(request, user)
            if next_page is not None:
                return redirect(next_page)
            else:
                return redirect('partners:dashboard')
    else:
        form = SigninForm
    return render(request, 'partners/sign_in.html', {'form': form})


@user_passes_test(is_partner, login_url='partners:sign_in')
def dashboard(request):
    partner = request.user.partner
    transactions = Transaction.objects.filter(perk__partner=partner).order_by('-date_created')
    return render(request, 'partners/dashboard.html',
                  {'partner': partner, 'transactions': transactions})


@user_passes_test(is_partner, login_url='partners:sign_in')
def my_perks(request):
    partner = request.user.partner
    perks = Perk.objects.filter(partner=request.user.partner)
    transactions_count = Transaction.objects.filter(perk__partner=partner).order_by('-date_created').count()
    return render(request, 'partners/my_perks.html',
                  {'perks': perks, 'transactions_count': transactions_count})


@user_passes_test(is_partner, login_url='partners:sign_in')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Пароль успешно изменен',
                             extra_tags='alert-success')
            return redirect('partners:change_password')
        else:
            messages.error(request,
                           'Ошибка. Пожалуйста, \
                           проверьте введённую информацию.',
                           extra_tags='alert-danger')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'partners/change_password.html', {
        'form': form
    })

partners/templates/partners/change_password.html
{% extends 'partners/partner_base.html' %}
{% load crispy_forms_tags %}

{% block dashboard-nav %}
<ul>
  <li><a href="{% url 'partners:dashboard' %}"><i class="fa fa-list"></i> Транзакции</a></li>
  <li><a href="{% url 'partners:my_perks' %}"><i class="fa fa-gift"></i> Предложения</a></li>
  <li class="active"><a id="MLabel" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user-o"></i> Аккаунт</a>
    <ul class="dropdown-menu" aria-labelledby="MLabel">
      <li><a href="{% url 'partners:change_password' %}"><i class="fa fa-key"></i> Сменить пароль</a></li>
    </ul>	
  </li>
  <li><a href="{% url 'partners:logout' %}"><i class="fa fa-power-off"></i> Выйти</a></li>
</ul>
{% endblock %}

{% block dashboard-content %}
<div class="row">
  <div class="col-md-6">
    <div class="add_listing_info">
      <form method="POST" action="" class="form-signin">
        {% csrf_token %}
        <h3>Сменить пароль</h3>
        {% if messages %}
          {% for message in messages %}
          <div class="alert alert-dismissable {{ message.tags }}">
            <strong>
            {{ message }}
            </strong>
          </div>
          {% endfor %}
        {% endif %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-block" value="Сохранить изменения">
      </form>
    </div>
  </div>
</div>
{% endblock %}

partners/templates/partners/dashboard.html
{% extends 'partners/partner_base.html' %}
{% load static %}

{% block extra_css %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'css/datatables.min.css' %}"/>
{% endblock %}

{% block dashboard-nav %}
  <ul>
    <li class="active"><a href="{% url 'partners:dashboard' %}"><i class="fa fa-list"></i> Транзакции</a></li>
    <li><a href="{% url 'partners:my_perks' %}"><i class="fa fa-gift"></i> Предложения</a></li>
    <li><a id="MLabel" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user-o"></i> Аккаунт</a>
      <ul class="dropdown-menu" aria-labelledby="MLabel">
        <li><a href="{% url 'partners:change_password' %}"><i class="fa fa-key"></i> Сменить пароль</a></li>
      </ul>	
    </li>
    <li><a href="{% url 'partners:logout' %}"><i class="fa fa-power-off"></i> Выйти</a></li>
  </ul>	
{% endblock %}
{% block dashboard-content %}
<div id="titlebar">
  <div class="row">
    <div class="col-md-12">
      <h2>Транзакции</h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table id="transactions_table" class="table table-bordered table-hover">
      <thead class="bg-info">
        <tr>
          <th class="col-md-2">Дата</th>
          <th class="col-md-2">Предложение</th>
          <th class="col-md-2">Имя</th>
          <th class="col-md-2">Фамилия</th>
          <th class="col-md-2">Компания</th>
          <th class="col-md-2">Код транзакции</th>
        </tr>
      </thead>
      <tbody>
        {% for t in transactions %}
        <tr>
          <td>{{ t.date_created }}</td>
          <td>{{ t.perk.title }}</td>
          <td>{{ t.member.first_name }}</td>
          <td>{{ t.member.last_name }}</td>
          <td>{{ t.member.company.name }}</td>
          <td><strong>{{ t.code }}</strong></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script>
<script type="text/javascript">
$(document).ready( function () {
    $('#transactions_table').DataTable({
			"language": {
					"decimal":        "",
					"emptyTable":     "У Вас пока нет транзакций",
					"info":           "Показано _START_ - _END_ из _TOTAL_ записей",
					"infoEmpty":      "Показано 0 - 0 из 0 записей",
					"infoFiltered":   "(фильтр из всего _MAX_ записей)",
					"infoPostFix":    "",
					"thousands":      ",",
					"lengthMenu":     "Показывать _MENU_ на странице",
					"loadingRecords": "Загрузка...",
					"processing":     "Обработка запроса...",
					"search":         "Поиск по коду:",
					"zeroRecords":    "Ничего не найдено",
					"paginate": {
							"first":      "Начало",
							"last":       "Конец",
							"next":       "Вперед",
							"previous":   "Назад"
					}
			},
      "order": [[ 0, "desc" ]],
});
} );
</script>
{% endblock %}

partners/templates/partners/my_perks.html
{% extends 'partners/partner_base.html' %}
{% load crispy_forms_tags %}

{% block dashboard-nav %}
<ul>
  <li><a href="{% url 'partners:dashboard' %}"><i class="fa fa-list"></i> Транзакции</a></li>
  <li class="active"><a href="{% url 'partners:my_perks' %}"><i class="fa fa-gift"></i> Предложения</a></li>
  <li><a id="MLabel" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user-o"></i> Аккаунт</a>
    <ul class="dropdown-menu" aria-labelledby="MLabel">
      <li><a href="{% url 'partners:change_password' %}"><i class="fa fa-key"></i> Сменить пароль</a></li>
    </ul>	
  </li>
  <li><a href="{% url 'partners:logout' %}"><i class="fa fa-power-off"></i> Выйти</a></li>
</ul>
{% endblock %}

{% block dashboard-content %}
<div id="titlebar">
  <div class="row">
    <div class="col-md-12">
      <h2>Активные предложения</h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="dashboard-info-box">
        <div class="dashboard-info color-1">
          <h4>{{ perks.count }}</h4> <span>Активных предложений</span>
        </div>
        <div class="dashboard-info color-4">
          <h4>{{ transactions_count }}</h4> <span>Использований</span>
        </div>
    </div>
  </div>
</div>

<div class="row">			
  <div class="col-md-12">
    {% for perk in perks %}
    <div class="dashboard-list-box">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th class="col-md-2">Наименование</th>
            <th class="col-md-8">{{ perk.title }} </th>
            <th class="col-md-2 text-center"><a class="button btn-block" href="{{ perk.get_absolute_url }}"><i class="fa fa-eye"></i>  Смотреть на сайте</a></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><strong>Количество использований</strong></td> 
            <td><p>{{ perk.transactions.count }}</p></td>
          </tr>
          <tr>
            <td><strong>Основное изображение</strong></td> 
            <td><img src="{{ perk.thumbnail }}"></td>
          </tr>
          <tr>
            <td><strong>Краткое описание</strong></td> 
            <td><p>{{ perk.short_description|default:"-" }}</p></td>
          </tr>
          <tr>
            <td><strong>Полное описание</strong></td> 
            <td>{{ perk.full_description|safe|default:"-" }}</p></td>
          </tr>
          <tr>
            <td><strong>Адрес</strong></td> 
            <td><p>{{ perk.address|default:"-" }}</p></td>
          </tr>
          <tr>
            <td><strong>Телефон</strong></td> 
            <td><p>{{ perk.phone_number|default:"-" }}</p></td>
          </tr>
          <tr>
            <td><strong>Веб-сайт</strong></td> 
            <td><p>{{ perk.website|default:"-" }}</p></td>
          </tr>
          <tr>
            <td><strong>Дата создания</strong></td> 
            <td><p>{{ perk.date_created|default:"-" }}</p></td>
          </tr>
        </tbody>
      </table>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

partners/templates/partners/partner_base.html
{% extends 'dashboard.html' %}

{% block logo-url %}
{% url 'partners:dashboard' %}
{% endblock %}

{% block navbar-title %}Панель управления{% endblock %}

{% block navbar-right %}
<div class="submit_listing">
    <a href="{% url 'partners:logout' %}" class="btn outline-btn">
        <i class="fa fa-sign-out"></i>&nbsp; Выйти
    </a>
</div>
{% endblock %}

{% block dashboard-nav %}
{% endblock %}

{% block dashboard-content %}

{% endblock %}

partners/templates/partners/sign_in.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section class="primary-bg">
	<div class="container">
    	<div id="login_signup">
            <div class="form_wrap_m">
            	<div class="white_box">
                	<h3>Вход для партнеров Benefits</h3>
                  {% if error %}
                  <div class="alert alert-dismissible alert-danger">
                    {{ error }}
                  </div>
                  {% endif %}
                  {% crispy form %}
                    <p><a href="lost-password">Забыли пароль?</a></p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}