benefits/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('customers.urls')),
    path('partner/', include('partners.urls')),
    path('account/', include('members.urls')),
    path('perks/', include('perks.urls')),
    path('', include('cms.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = settings.ADMIN_SITE_HEADER

cms/urls.py
from django.conf.urls import url

from . import views

app_name = 'cms'

urlpatterns = [
    url(r'^$', views.index.as_view(), name='index'),
]

customers/urls.py
from django.conf.urls import url

from . import views

app_name = 'customers'

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^delete/$', views.delete_members, name='delete_members'),
    url(r'^delete_ajax/$', views.delete_member_ajax,
        name='delete_member_ajax'),
    url(r'^switch_status_ajax/$', views.switch_status_ajax,
        name='switch_status_ajax'),
    url(r'^add/$', views.add_members, name='add_members'),
]

members/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'members'

urlpatterns = [
    url(r'^sign_in/', views.sign_in, name='sign_in'),
    url(r'^activate', views.activate, name='activate'),
    url(r'^register/', views.register, name='register'),
    url(r'^success/', views.registration_success.as_view(), name='success'),
    url(r'^edit/', views.edit_info, name='edit_info'),
    url(r'^logout/', auth_views.LogoutView.as_view(),
        {'next_page': '/account/sign_in/'}, name='logout'),
    url(r'^change_password/', views.change_password, name='change_password'),
    url(r'^my_perks/', views.my_perks, name='my_perks'),
]

perks/urls.py
from django.conf.urls import url

from . import views

app_name = 'perks'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.perk_detail.as_view(),
        name='perk_detail'),
    url(r'^modal/(?P<pk>[0-9]+)/$', views.perk_modal,
        name='perk_modal'),
    url(r'^get/(?P<pk>[0-9]+)/$', views.get_perk,
        name='get_perk'),
    url(r'^(?P<category>[\w-]+)/$', views.index, name='category'),
]

perks/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import string
from django.utils.crypto import get_random_string
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from django.urls import reverse
from geoposition.fields import GeopositionField
import sendgrid
from sendgrid.helpers.mail import Mail, Email, Personalization, Substitution
import urllib.request as urllib

from partners.models import Partner
from tinymce.models import HTMLField
from members.models import Member

sg = sendgrid.SendGridAPIClient(settings.SENDGRID_API_KEY)


class PerkCategory(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    slug = models.SlugField(max_length=50, verbose_name='SLUG')
    icon = models.FileField(upload_to='category_icons/',
                            verbose_name='SVG иконка',
                            blank=True, null=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def icon_url(self):
        return self.icon.url

    def get_absolute_url(self):
        return reverse('perks:category', kwargs={'category': self.slug})


class Perk(models.Model):
    partner = models.ForeignKey(Partner, on_delete=models.CASCADE, null=True,
                                blank=True, related_name='perks',
                                verbose_name='Партнер')
    category = models.ForeignKey(PerkCategory, on_delete=models.SET_NULL,
                                 null=True, blank=True, related_name='perks',
                                 verbose_name='Категория')
    title = models.CharField(max_length=200, verbose_name="Заголовок")
    discount = models.CharField(max_length=200, verbose_name='Скидка',
                                blank=True, null=True)
    short_description = models.CharField(max_length=200,
                                         verbose_name='Краткое описание',
                                         blank=True, null=True)
    full_description = HTMLField(verbose_name='Полное описание',
                                 null=True, blank=True)
    address = models.CharField(max_length=200, verbose_name='Адрес',
                               null=True, blank=True)
    phone_number = models.CharField(max_length=200, verbose_name='Телефон',
                                    null=True, blank=True)
    website = models.URLField(verbose_name='Веб-сайт', null=True, blank=True)
    geoposition = GeopositionField(verbose_name='Геолокация',
                                   null=True, blank=True)
    active = models.BooleanField(default=True,
                                 verbose_name='Предложение активно')
    date_created = models.DateTimeField(null=True, blank=True,
                                        auto_now_add=True,
                                        verbose_name='Дата создания')

    class Meta:
        verbose_name = 'Предложения'
        verbose_name_plural = 'Предложения'

    def __str__(self):
        return self.title

    @property
    def thumbnail(self):
        if self.images.first():
            return self.images.first().img.url

    def get_absolute_url(self):
        return reverse('perks:perk_detail', kwargs={'pk': self.pk})

    def get_modal_url(self):
        return reverse('perks:perk_modal', kwargs={'pk': self.pk})

    def get_perk_url(self):
        return reverse('perks:get_perk', kwargs={'pk': self.pk})

    def partner_name(self):
        return self.partner.name
    partner_name.short_description = 'Партнер'


class PerkImage(models.Model):
    perk = models.ForeignKey(Perk, on_delete=models.CASCADE,
                             related_name='images')
    img = models.ImageField(upload_to='perks/', verbose_name='Файл')

    def thumbnail(self):
        return u'<img src="%s" width=100 height=100 />' % (self.img.url)

    thumbnail.short_description = 'Предпросмотр'
    thumbnail.allow_tags = True

    class Meta:
        verbose_name = 'картинка'
        verbose_name_plural = 'Картинки'

    def __str__(self):
        return self.img.url


def generate_code():
    allowed_chars = string.ascii_uppercase.replace("O", "") + string.digits
    while True:
        code = get_random_string(length=4, allowed_chars=allowed_chars)
        try:
            Transaction.objects.get(code=code)
        except ObjectDoesNotExist:
            return code


class Transaction(models.Model):
    member = models.ForeignKey(Member, on_delete=models.CASCADE,
                               related_name='transactions',
                               verbose_name='Сотрудник')
    perk = models.ForeignKey(Perk, on_delete=models.DO_NOTHING,
                             related_name='transactions',
                             verbose_name='Предложение')
    date_created = models.DateTimeField(auto_now_add=True,
                                        verbose_name='Дата и время')
    code = models.CharField(max_length=4,
                            default=generate_code,
                            verbose_name='Код транзакции')

    class Meta:
        verbose_name = 'Транзакция'
        verbose_name_plural = 'Транзакции'

    def __str__(self):
        return self.code

    def notify_member(self):
        mail = Mail()
        mail.from_email = Email('info@benefits.kz')
        personalization = Personalization()
        personalization.add_to(Email('o.arystanov@gmail.com'))
        #personalization.add_to(Email(self.member.user.email))
        mail.add_personalization(personalization)
        mail.template_id = settings.SENDGRID_TEMPLATES['activation']
        try:
            response = sg.client.mail.send.post(request_body=mail.get())
        except urllib.HTTPError as e:
            print(e.read())
            exit()
        print(response.status_code)
        print(response.body)
        print(response.headers)

perks/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import user_passes_test
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.detail import DetailView

from .models import Perk, PerkCategory, Transaction
from members.views import is_member


def index(request, category=None):
    if category is not None:
        category = get_object_or_404(PerkCategory, slug=category)
        perk_list = Perk.objects.filter(category=category, active=True)
    else:
        perk_list = Perk.objects.filter(active=True)
    perk_list = perk_list.order_by('-date_created')
    paginator = Paginator(perk_list, 9)
    page = request.GET.get('page')
    try:
        perks = paginator.page(page)
    except PageNotAnInteger:
        perks = paginator.page(1)
    except EmptyPage:
        perks = paginator.page(paginator.num_pages)
    categories = PerkCategory.objects.all()
    return render(request, 'perks/index.html',
                  {'perks': perks, 'categories': categories,
                   'active_category': category})


class perk_detail(DetailView):

    model = Perk


@user_passes_test(is_member, login_url='members:sign_in')
@user_passes_test(lambda user: user.is_active, login_url='members:register')
def perk_modal(request, pk):
    perk = get_object_or_404(Perk, pk=pk)
    return render(request, 'perks/partials/modal.html', {'perk': perk})


@user_passes_test(is_member, login_url='members:sign_in')
@user_passes_test(lambda user: user.is_active, login_url='members:register')
def get_perk(request, pk):
    perk = get_object_or_404(Perk, pk=pk)
    transaction = Transaction(member=request.user.member,
                              perk=perk)
    transaction.save()
    transaction.notify_member()
    return render(request, 'perks/result.html',
                  {'transaction_code': transaction.code})

perks/templates/perks/partials/modal.html
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal">&times;</button>
  <h4 class="modal-title">Получить предложение?</h4>
</div>
<div class="modal-body">
  <p class="lead" id="perk_info"><strong>{{ perk.partner.name }}</strong>: {{ perk.title }}</p>
  <hr>
  <p>Уникальный 4-х значный код для получения предложения придет на ваш
  электронный адрес: <a>{{ request.user.email }}</a>.</p> 
</div>
<div class="modal-footer">
  <div class="row">
      <a class="btn back_btn" data-dismiss="modal">Отмена</a>
      <a class="btn get_perk_btn" href="{{ perk.get_perk_url }}">Получить</a>
  </div>
</div>

perks/templates/perks/partials/modals.html
<div id="add_perk_modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Получить предложение</h4>
      </div>
      <div class="modal-body">
        <p class="lead" id="perk_info"><strong>{{ perk.partner.name }}</strong>: {{ perk.title }}</p>
        <hr>
        <p>Уникальный 4-х значный код для получения предложения придет на ваш
        электронный адрес: <a>{{ request.user.email }}</a>.</p> 
        <p>Если на Вашем смартфоне
        установлено приложение Benefits, код предложения будет также доступен
        в приложении.</p>
      </div>
      <div class="modal-footer">
        <div class="row">
          <div class="col-md-3 col-md-offset-6">
            <form method="POST" id="get_perk_form" action="{{ perk.get_absolute_url }}" class="pull-right">
            {% csrf_token %}
            <input type="hidden" id="perk_id" value="">
            <button type="submit" class="btn">Получить</button>
            </form>
          </div>
          <div class="col-md-3">
            <a class="btn btn-default" data-dismiss="modal">Отмена</a>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

<div id="result_modal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body"> 
        {% if messages %}
          {% for message in messages %}
            {% if message.level == 25 %}
              <p>Поздравляем! Ваш код для получения скидки:</p>
              <p class="lead"><strong>{{ message }}</strong></p>
              <p>Код также был отправлен на Ваш электронный адрес: 
              <a>{{ request.user.email }}</a></p>
              <p class="lead">Спасибо что пользуетесь сервисом Benefits!</p>
            {% elif message.level == 40 %}
              <p class="text-danger">Произошла ошибка</p>
              <p>Приносим свои извинения за предоставленные неудобства. Попробуйте повторить попытку позднее.</p>
              <p>Если ошибка повторится, напишите нам на:
              <a href="mailto:support@benefits.kz"> support@benefits.kz</a>
              </p>
            {% endif %}
          {% endfor %}
        {% endif %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Готово</button>
      </div>
    </div>

  </div>
</div>

{% block extra_js %}
{% if messages %}
<script type="text/javascript">
    $(window).on('load',function(){
        $('#result_modal').modal('show');
    });
</script>
{% endif %}
{% endblock %}

perks/templates/perks/partials/navigation.html
<header id="header">
  <nav class="navbar navbar-default">
    <div class="container">
      <div class="navbar-header">
          <div class="logo"> <a href="{% url 'perks:index' %}">Benefits</a> 
          {% if request.user.member.company %}
          <a><img class="customer_logo"  src="{{ request.user.member.company.logo.url }}"></a>
          {% endif %}
          </div>
          <div>
          </div>
        <button id="menu_slide" data-target="#navigation" aria-expanded="false" data-toggle="collapse" class="navbar-toggle collapsed" type="button"> 
            <span class="sr-only">Toggle navigation</span> 
            <span class="icon-bar"></span> 
            <span class="icon-bar"></span> 
            <span class="icon-bar"></span> 
        </button>
      </div>

      <div class="collapse navbar-collapse" id="navigation">
        {% if request.user.is_company_admin %}
        <ul class="nav navbar-nav pull-left">
          <li><a href="{% url 'customers:dashboard' %}"><i class="fa fa-cogs"></i>Панель управления</a></li>
        </ul>
        {% endif %}
        {% if request.user.is_member %}
        <ul class="nav navbar-nav">
          <li><a href="{% url 'members:my_perks' %}"><i class="fa fa-gift"></i>Мои предложения</a></li>
          <li class="menu-item-has-children">
            <a href="#"><i class="fa fa-user-o"></i>{{ request.user.email }}</a> <span class="arrow"></span>
             <ul class="sub-menu">
                <li><a href="{% url 'members:edit_info' %}">Управление аккаунтом</a></li>
                <li><a href="{% url 'members:change_password' %}">Смена пароля</a></li>
                <li><a href="{% url 'members:logout' %}">Выход</a></li>
            </ul> 
          </li>
        </ul>
        {% else %}
          <div class="submit_listing">
          <a class="btn login_btn" href="{% url 'members:sign_in' %}"><i class="fa fa-sign-in"></i>&nbsp;Вход</a>
          </div>
        {% endif %}
      </div>
    </div>
  </nav>
</header>