benefits/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('customers.urls')),
    path('partner/', include('partners.urls')),
    path('account/', include('members.urls')),
    path('perks/', include('perks.urls')),
    path('', include('cms.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = settings.ADMIN_SITE_HEADER

cms/urls.py
from django.conf.urls import url

from . import views

app_name = 'cms'

urlpatterns = [
    url(r'^$', views.index.as_view(), name='index'),
]

customers/urls.py
from django.conf.urls import url

from . import views

app_name = 'customers'

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^delete/$', views.delete_members, name='delete_members'),
    url(r'^delete_ajax/$', views.delete_member_ajax,
        name='delete_member_ajax'),
    url(r'^switch_status_ajax/$', views.switch_status_ajax,
        name='switch_status_ajax'),
    url(r'^add/$', views.add_members, name='add_members'),
]

members/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'members'

urlpatterns = [
    url(r'^sign_in/', views.sign_in, name='sign_in'),
    url(r'^activate', views.activate, name='activate'),
    url(r'^register/', views.register, name='register'),
    url(r'^success/', views.registration_success.as_view(), name='success'),
    url(r'^edit/', views.edit_info, name='edit_info'),
    url(r'^logout/', auth_views.LogoutView.as_view(),
        {'next_page': '/account/sign_in/'}, name='logout'),
    url(r'^change_password/', views.change_password, name='change_password'),
    url(r'^my_perks/', views.my_perks, name='my_perks'),
]

customers/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings


class Company(models.Model):
    admin = models.OneToOneField(settings.AUTH_USER_MODEL,
                                 on_delete=models.CASCADE,
                                 verbose_name='Администратор')
    name = models.CharField(max_length=100, verbose_name='Наименование')
    address = models.CharField(max_length=200, verbose_name='Адрес',
                               blank=True, null=True)
    logo = models.ImageField(upload_to='customers/logos',
                             verbose_name='Логотип',
                             blank=True, null=True)

    class Meta:
        ordering = ['name', ]
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'

    def __str__(self):
        return self.name

    def total_members_count(self):
        return self.members.count()
    total_members_count.short_description = 'Количество сотрудников'

    @property
    def active_members_count(self):
        return self.members.filter(enabled=True, user__is_active=True).count()

    @property
    def pending_registration_count(self):
        return self.members.filter(user__is_active=False).count()

    @property
    def transactions_count(self):
        return sum([n.transactions_count for n in self.members.all()])

customers/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import user_passes_test
from members.models import Member
from django.http import HttpResponseRedirect, HttpResponse, \
    HttpResponseForbidden
from django.core.exceptions import ObjectDoesNotExist
from .utils import create_members_from_list, create_members_from_file


def is_admin(user):
    if user.is_anonymous:
        return False
    else:
        return user.is_company_admin


@user_passes_test(is_admin, login_url='members:sign_in')
def dashboard(request):
    company = request.user.member.company
    return render(request, 'customers/dashboard.html', {'company': company})


@user_passes_test(is_admin, login_url='members:sign_in')
def delete_members(request):
    if request.method == 'POST':
        to_delete = request.POST.getlist('to_delete')
        for member_pk in to_delete:
            try:
                member = Member.objects.get(pk=member_pk)
            except ObjectDoesNotExist:
                pass
            else:
                member.user.delete()
                # delete User & Member instance
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@user_passes_test(is_admin, login_url='members:sign_in')
def delete_member_ajax(request):
    if request.is_ajax():
        if request.method == 'POST':
            member_pk = request.POST.get('pk')
            try:
                member = Member.objects.get(pk=member_pk)
            except ObjectDoesNotExist:
                pass
            else:
                member.user.delete()
            return HttpResponse(request.META.get('HTTP_REFERER'))
    return HttpResponseForbidden()


@user_passes_test(is_admin, login_url='members:sign_in')
def switch_status_ajax(request):
    if request.is_ajax():
        if request.method == 'POST':
            member_pk = request.POST.get('pk')
            try:
                member = Member.objects.get(pk=member_pk)
            except ObjectDoesNotExist:
                pass
            else:
                member.switch_status()
            return HttpResponse(request.META.get('HTTP_REFERER'))
    return HttpResponseForbidden()


@user_passes_test(is_admin, login_url='members:sign_in')
def add_members(request):
    if request.method == 'POST':
        company = request.user.member.company
        if 'members_list' in request.POST:
            create_members_from_list(request,
                                     request.POST.get('members_list'), company)
        elif 'members_file' in request.FILES:
            create_members_from_file(request,
                                     request.FILES['members_file'], company)
        return redirect('customers:dashboard')
    return render(request, 'customers/add_members.html')

customers/templates/customers/add_members.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block navbar-title %}Панель управления{% endblock %}

{% block dashboard-nav %}
  <ul>
    {% if request.user.is_company_admin %}
    <li class="active"><a href="{% url 'customers:dashboard' %}"><i class="fa fa-cogs"></i> Панель управления</a></li>
    {% endif %}
    <li><a href="{% url 'members:my_perks' %}"><i class="fa fa-gift"></i> Мои предложения</a></li>
    <li><a id="MLabel" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user-o"></i> Аккаунт</a>
      <ul class="dropdown-menu" aria-labelledby="MLabel">
        <li><a href="{% url 'members:edit_info' %}"><i class="fa fa-edit"></i> Редактировать</a></li>
        <li><a href="{% url 'members:change_password' %}"><i class="fa fa-key"></i> Сменить пароль</a></li>
      </ul>	
    </li>
    <li><a href="{% url 'members:logout' %}"><i class="fa fa-power-off"></i> Выйти</a></li>
  </ul>	
{% endblock %}
{% block dashboard-content %}
<div id="titlebar">
  <div class="row">
    <div class="col-md-12">
      <h2>{{ request.user.member.company.name }} <small>&emsp;Добавление сотрудников</small></h2>
    </div>
  </div>
</div>
<div class="row">
    <div class="col-md-6">
      <div class="add_listing_info">
        <h3>Добавить вручную</h3>
          <p>
        Заполните электронные адреса сотрудников в поле ниже (каждый новый адрес
        необходимо добавлять с новой строки):
          </p>
          <form action="" method="POST">
            {% csrf_token %}
            <textarea class="form-control" rows="10" name="members_list" id="members_list"></textarea>
            <br>
            <input type="submit" class="btn" value="Добавить">
          </form>
			</div>
    </div>
    <div class="col-md-6">
      <div class="add_listing_info">
        <h3>Импорт из CSV-файла</h3>
          <p>
            Загрузите CSV-файл с электронными адресами сотрудников:
          </p>
          <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <input type="file" id="members_file" name="members_file" value="Выберите файл">     
            <br>
            <input type="submit" class="btn" value="Импортировать">
          </form>
			</div>
		</div>
  </div>
{% endblock %}

customers/templates/customers/dashboard.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags static %}

{% block extra_css %}
{{ block.super }}
<link rel="stylesheet" type="text/css" href="{% static 'css/datatables.min.css' %}"/>
{% endblock %}

{% block navbar-title %}Панель управления{% endblock %}

{% block dashboard-nav %}
<ul>
  {% if request.user.is_company_admin %}
  <li class="active"><a href="{% url 'customers:dashboard' %}"><i class="fa fa-cogs"></i> Панель управления</a></li>
  {% endif %}
  <li><a href="{% url 'members:my_perks' %}"><i class="fa fa-gift"></i> Мои предложения</a></li>
  <li><a id="MLabel" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user-o"></i> Аккаунт</a>
    <ul class="dropdown-menu" aria-labelledby="MLabel">
      <li><a href="{% url 'members:edit_info' %}"><i class="fa fa-edit"></i> Редактировать</a></li> <li><a href="{% url 'members:change_password' %}"><i class="fa fa-key"></i> Сменить пароль</a></li>
    </ul>	
  </li>
  <li><a href="{% url 'members:logout' %}"><i class="fa fa-power-off"></i> Выйти</a></li>
</ul>	
{% endblock %}
{% block dashboard-content %}
<div id="titlebar">
  <div class="row">
    <div class="col-md-12">
      <h2>Статистика<small>&emsp;{{ company.name }}</small></h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="dashboard-info-box">
      <div class="dashboard-info color-1">
        <h4>{{ company.transactions_count }}</h4> <span>Предложений использовано</span>
      </div>
      <div class="dashboard-info color-4">
        <h4>{{ company.active_members_count }}</h4> <span>Активных аккаунтов</span>
      </div>
      <div class="dashboard-info color-5">
        <h4>{{ company.pending_registration_count }}</h4> <span>Ожидают регистрации</span>
      </div>
    </div>
  </div>
</div>

<hr>

<div id="titlebar">
  <div class="row">
    <div class="col-md-12">
      <h2>Сотрудники</h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <table id="employees_table" data-order='[[ 0, "asc" ]]' data-page-length='10' class="table table-bordered table-hover">
      <thead class="bg-info">
        <tr>
          <th class="col-md-1">#</th>
          <th class="col-md-3">Email</th>
          <th class="col-md-4">Фамилия, Имя</th>
          <th class="col-md-2">Доступ к сервису</th>
          <th class="col-md-2"></th>
        </tr>
      </thead>
      <tbody>
        {% for member in company.members.all %}
        <tr id="row_{{ member.pk }}" {% if not member.enabled %}class="bg-danger"{% endif %}>
          <td>{{ forloop.counter }}</td>
          <td>{{ member.email }}</td>
          <td>{{ member.full_name|default:'<span class="label label-warning">Ожидает регистрации</span>' }}</td>
          <td>
            {% if member.enabled %}
            <span class="label label-success">Активен</span>
            {% else %} 
            <span class="label label-default"><b>Отключен</b></span>
            {% endif %}
          </td>
          <td>
            {% if member.is_admin %}
            <span class="label label-info">Администратор</span> 
            {% else %}
            <a href="" class="text-warning btn_disable switch_member" data-pk="{{ member.pk }}" {% if not member.enabled %}hidden{% endif %}><i class='fa fa-ban'></i> Отключить</a>
            <a href="" class="text-primary btn_enable switch_member" data-pk="{{ member.pk }}" {% if member.enabled %}hidden{% endif %}><i class='fa fa-plug'></i> Включить</a>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
<br>
{% endblock %}

{% block modal %}

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body col-md-12">
        {% if messages %}
        {% for message in messages %}
        <p class="{{ message.tags }}">
        <strong>
          {{ message }}
        </strong>
        </p>
        {% endfor %}
        {% endif %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть окно</button>
      </div>
    </div>

  </div>
</div>

{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'js/datatables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/dataTables.buttons.min.js' %}"></script>
<script type="text/javascript">
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
      var cookies = document.cookie.split(';');
      for (var i = 0; i < cookies.length; i++) {
        var cookie = jQuery.trim(cookies[i]);
        // Does this cookie string begin with the name we want?
        if (cookie.substring(0, name.length + 1) === (name + '=')) {
          cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
          break;
        }
      }
    }
    return cookieValue;
  }
function csrfSafeMethod(method) {
  // these HTTP methods do not require CSRF protection
  return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$(document).ready( function () {
  var table = $('#employees_table').DataTable({
    "language": {
      "decimal":        "",
      "emptyTable":     "У Вас пока нет сотрудников",
      "info":           "Показано _START_ - _END_ из _TOTAL_ записей",
      "infoEmpty":      "Показано 0 - 0 из 0 записей",
      "infoFiltered":   "(фильтр из всего _MAX_ записей)",
      "infoPostFix":    "",
      "thousands":      ",",
      "lengthMenu":     "Показывать _MENU_ на странице",
      "loadingRecords": "Загрузка...",
      "processing":     "Обработка запроса...",
      "search":         "Поиск:",
      "zeroRecords":    "Ничего не найдено",
      "paginate": {
        "first":      "Начало",
        "last":       "Конец",
        "next":       "Вперед",
        "previous":   "Назад"
      }
    },
    "lengthChange": false,
    buttons: [
      {
        text: '<i class="fa fa-plus"></i> Добавить сотрудников',
        action: function ( e, dt, button, config ) {
          window.location = "{% url 'customers:add_members' %}";
        },
        className: "btn btn-sm",
      }
    ]
  });
  table.buttons().container()
    .appendTo( $('.col-sm-6:eq(0)', table.table().container() ) );
  var csrftoken = getCookie('csrftoken');
  $(".delete_member").click(function() {
    if (confirm('Удалить выбранного сотрудника?')) {
      $.ajax({
        beforeSend: function(xhr, settings) {
          if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
          }
        },
        type: "POST",
        url: "{% url 'customers:delete_member_ajax' %}",
        data: {
          'pk': $(this).attr('id')
        }
      });
      $(this).closest('tr').remove();
    };
  });
  $(".btn_enable").click(function() {
    event.preventDefault();
    if (confirm('Включить доступ к сервису для данного сотрудника?')) {
      $.ajax({
        beforeSend: function(xhr, settings) {
          if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
          }
        },
        type: "POST",
        url: "{% url 'customers:switch_status_ajax' %}",
        data: {
          'pk': $(this).attr('data-pk')
        }
      });
      $(this).hide();
      $(this).siblings('.btn_disable').show();
      $(this).parent().prev().html('<span class="label label-success">Активен</span>');
      $(this).closest('tr').removeClass('bg-danger');
    };
  });
  $(".btn_disable").click(function() {
    event.preventDefault();
    if (confirm('Отключить доступ к сервису для данного сотрудника?')) {
      $.ajax({
        beforeSend: function(xhr, settings) {
          if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
          }
        },
        type: "POST",
        url: "{% url 'customers:switch_status_ajax' %}",
        data: {
          'pk': $(this).attr('data-pk')
        }
      });
      $(this).hide();
      $(this).siblings('.btn_enable').show();
      $(this).parent().prev().html('<span class="label label-default">Отключен</span>');
      $(this).closest('tr').addClass('bg-danger');
    };
  });
} );
</script>
{% if messages %}
<script type="text/javascript">
  $(window).on('load',function(){
    $('#myModal').modal('show');
  });
</script>
{% endif %}
{% endblock %}