benefits/urls.py
from django.urls import path
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('customers.urls')),
    path('partner/', include('partners.urls')),
    path('account/', include('members.urls')),
    path('perks/', include('perks.urls')),
    path('', include('cms.urls')),
    path('tinymce/', include('tinymce.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = settings.ADMIN_SITE_HEADER

cms/urls.py
from django.conf.urls import url

from . import views

app_name = 'cms'

urlpatterns = [
    url(r'^$', views.index.as_view(), name='index'),
]

customers/urls.py
from django.conf.urls import url

from . import views

app_name = 'customers'

urlpatterns = [
    url(r'^$', views.dashboard, name='dashboard'),
    url(r'^delete/$', views.delete_members, name='delete_members'),
    url(r'^delete_ajax/$', views.delete_member_ajax,
        name='delete_member_ajax'),
    url(r'^switch_status_ajax/$', views.switch_status_ajax,
        name='switch_status_ajax'),
    url(r'^add/$', views.add_members, name='add_members'),
]

members/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'members'

urlpatterns = [
    url(r'^sign_in/', views.sign_in, name='sign_in'),
    url(r'^activate', views.activate, name='activate'),
    url(r'^register/', views.register, name='register'),
    url(r'^success/', views.registration_success.as_view(), name='success'),
    url(r'^edit/', views.edit_info, name='edit_info'),
    url(r'^logout/', auth_views.LogoutView.as_view(),
        {'next_page': '/account/sign_in/'}, name='logout'),
    url(r'^change_password/', views.change_password, name='change_password'),
    url(r'^my_perks/', views.my_perks, name='my_perks'),
]

perks/urls.py
from django.conf.urls import url

from . import views

app_name = 'perks'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.perk_detail.as_view(),
        name='perk_detail'),
    url(r'^modal/(?P<pk>[0-9]+)/$', views.perk_modal,
        name='perk_modal'),
    url(r'^get/(?P<pk>[0-9]+)/$', views.get_perk,
        name='get_perk'),
    url(r'^(?P<category>[\w-]+)/$', views.index, name='category'),
]

members/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
import hashlib
import random
from django.core.validators import RegexValidator
from django.urls import reverse
import sendgrid
from sendgrid.helpers.mail import Mail, Email, Personalization, Substitution
import urllib.request as urllib

from customers.models import Company

sg = sendgrid.SendGridAPIClient(settings.SENDGRID_API_KEY)
phone_validator = RegexValidator(r"^[0-9]{10}$")


class Member(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                verbose_name='Учетная запись')
    company = models.ForeignKey(Company,
                                on_delete=models.CASCADE,
                                verbose_name='Компания',
                                related_name='members')
    first_name = models.CharField(max_length=100, verbose_name='Имя',
                                  null=True)
    last_name = models.CharField(max_length=200, verbose_name='Фамилия',
                                 null=True)
    phone_number = models.CharField(max_length=20,
                                    verbose_name='Номер телефона',
                                    null=True,
                                    validators=[phone_validator])
    date_of_birth = models.DateField(verbose_name='Дата рождения',
                                     null=True)
    activation_token = models.CharField(max_length=200, verbose_name='Токен',
                                        editable=False)
    enabled = models.BooleanField(default=True, editable=False,
                                  verbose_name='Включен')

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'
        ordering = ['-enabled', 'pk']

    def __str__(self):
        return self.user.email

    def generate_token(self):
        # Generating activation key
        # First generate random part as a result of hashing random string
        random_string = str(random.random()).encode('utf-8')
        random_part = hashlib.sha256(random_string).hexdigest()[:5]
        hashable = random_part.encode('utf-8') + \
            self.user.email.encode('utf-8')
        # Then create hash for random_part and email
        self.activation_token = hashlib.sha256(hashable).hexdigest()
        self.save()

    def switch_status(self):
        if self.enabled:
            self.enabled = False
        else:
            self.enabled = True
        self.save()

    @property
    def full_name(self):
        if self.last_name and self.first_name:
            return self.last_name + ' ' + self.first_name

    @property
    def email(self):
        return self.user.email

    @property
    def transactions_count(self):
        return self.transactions.count()

    def activate(self):
        user = self.user
        user.is_active = True
        user.save()

    @property
    def is_active(self):
        return self.user.is_active

    @property
    def is_admin(self):
        return self.company.admin == self.user

    def notify_activation(self):
        mail = Mail()
        mail.from_email = Email('info@benefits.kz')
        personalization = Personalization()
        personalization.add_to(Email('o.arystanov@gmail.com'))
        #personalization.add_to(Email(self.user.email))
        activation_link = 'http://127.0.0.1:8000' + \
            reverse('members:activate') + \
            '?pk={pk}&token={token}'.format(
                pk=self.pk, token=self.activation_token
            )
        personalization.add_substitution(
            Substitution('%activation_link%', activation_link)
        )
        mail.add_personalization(personalization)
        mail.template_id = settings.SENDGRID_TEMPLATES['activation']
        try:
            response = sg.client.mail.send.post(request_body=mail.get())
        except urllib.HTTPError as e:
            print(e.read())
            exit()
        print(response.status_code)
        print(response.body)
        print(response.headers)

    def notify_registration_complete(self):
        mail = Mail()
        mail.from_email = Email('info@benefits.kz')
        personalization = Personalization()
        personalization.add_to(Email('o.arystanov@gmail.com'))
        #personalization.add_to(Email(self.user.email))
        mail.add_personalization(personalization)
        mail.template_id = settings.SENDGRID_TEMPLATES['registration_complete']
        try:
            response = sg.client.mail.send.post(request_body=mail.get())
        except urllib.HTTPError as e:
            print(e.read())
            exit()
        print(response.status_code)
        print(response.body)
        print(response.headers)

members/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth import authenticate
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit
from .models import Member


class RegisterForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['first_name', 'last_name', 'phone_number', 'date_of_birth']

    password = forms.CharField(max_length=32, label='Пароль',
                               widget=forms.PasswordInput)
    password2 = forms.CharField(max_length=32, label='Повтор пароля',
                                widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(RegisterForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_show_labels = False
        self.helper.add_input(Submit('submit', 'Зарегистрироваться',
                                     css_class='btn btn-block'))
        layout = self.helper.layout = Layout()
        for field_name, field in self.fields.items():
            layout.append(Field(field_name, placeholder=field.label))

    def clean(self):
        cleaned_data = super(RegisterForm, self).clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")
        if password != password2:
            raise forms.ValidationError('Введенные пароли не совпадают')


class EditForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['first_name', 'last_name', 'phone_number', 'date_of_birth']


class SigninForm(forms.Form):
    email = forms.EmailField(label='Email')
    password = forms.CharField(label='Пароль',
                               max_length=32, widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(SigninForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_show_labels = False
        self.helper.add_input(Submit('submit',
                                     'Войти', css_class='btn btn-block'))
        layout = self.helper.layout = Layout()
        for field_name, field in self.fields.items():
            layout.append(Field(field_name, placeholder=field.label))

    def clean(self):
        cleaned_data = super(SigninForm, self).clean()
        email = cleaned_data['email']
        password = cleaned_data['password']
        user_cache = authenticate(username=email, password=password)
        if user_cache is None:
            raise forms.ValidationError('Вы ввели неверный e-mail или пароль')
        if not user_cache.is_member:
            raise forms.ValidationError('У вашей учетной записи недостаточно прав \
                                  для просмотра данной страницы')

members/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib import messages
from django.views.generic import TemplateView
from .models import Member
from .forms import EditForm, RegisterForm, SigninForm


def is_member(user):
    if user.is_anonymous:
        return False
    else:
        return user.is_member


def sign_in(request):
    if request.user.is_authenticated and request.user.is_member:
        return redirect('perks:index')
    next_page = request.GET.get('next')
    if request.method == 'POST':
        form = SigninForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, username=email, password=password)
            login(request, user)
            if next_page is not None:
                return redirect(next_page)
            else:
                return redirect('perks:index')
    else:
        form = SigninForm
    return render(request, 'members/sign_in.html', {'form': form})


def activate(request):
    if request.method == 'GET':
        pk = request.GET.get('pk')
        token = str(request.GET.get('token'))
        try:
            member = Member.objects.get(pk=pk, activation_token=token)
            if member is not None:
                if member.is_active:
                    return redirect('perks:index')
                else:
                    login(request, member.user)
                    return redirect('members:register')
        except ObjectDoesNotExist:
            pass
    return HttpResponseForbidden()


@login_required(login_url='members:sign_in')
def register(request):
    if request.method == 'POST':
        member = request.user.member
        form = RegisterForm(request.POST, instance=member)
        if form.is_valid():
            form.save()
            member.user.set_password(form.cleaned_data['password'])
            member.activate()
            login(request, member.user)
            return redirect('members:success')
        else:
            messages.error(request,
                            'Ошибка. Пожалуйста, \
                            проверьте введённую информацию.',
                            extra_tags='alert-danger')
    form = RegisterForm()
    return render(request, 'members/register.html', {'form': form})


class registration_success(TemplateView):
    template_name = 'members/registration_success.html'


@user_passes_test(is_member, login_url='members:sign_in')
@user_passes_test(lambda user: user.is_active, login_url='members:register')
def edit_info(request):
    member = request.user.member
    if request.method == 'POST':
        form = EditForm(request.POST, instance=member)
        if form.is_valid():
            form.save()
            messages.success(request, 'Информация успешно обновлена',
                             extra_tags='alert-success')
            return redirect('members:edit_info')
        else:
            messages.error(request,
                           'Ошибка. Пожалуйста, \
                           проверьте введённую информацию.',
                           extra_tags='alert-danger')
    else:
        form = EditForm(instance=member)
    return render(request, 'members/edit_info.html', {'form': form})


@user_passes_test(is_member, login_url='members:sign_in')
@user_passes_test(lambda user: user.is_active, login_url='members:register')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Пароль успешно изменен',
                             extra_tags='alert-success')
            return redirect('members:change_password')
        else:
            messages.error(request,
                           'Ошибка. Пожалуйста, \
                           проверьте введённую информацию.',
                           extra_tags='alert-danger')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'members/change_password.html', {
        'form': form
    })


@user_passes_test(is_member, login_url='members:sign_in')
@user_passes_test(lambda user: user.is_active, login_url='members:register')
def my_perks(request):
    transactions = request.user.member.transactions.order_by('-date_created')
    return render(request, 'members/my_perks.html',
                  {'transactions': transactions})

members/templates/members/base.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}" type="text/css">
{% endblock %}

{% block content %}
<div class="dashboard_container">
  <header id="header">
          <nav class="navbar navbar-default navbar-fixed-top">
              <div class="container">
                 <div class="navbar-header">
                  <div class="logo"> 
                    <a href="{% url 'perks:index' %}"><img src="assets/images/logo.png" alt="Benefits"/></a> 
                  </div>
                  <div id="dashboard-responsive-nav-trigger"><i class="fa fa-reorder"></i></div>
                </div>
                  <div class="collapse navbar-collapse" id="navigation">
                    <div class="submit_listing">
                        <a href="{% url 'perks:index' %}" class="btn outline-btn">
                            <i class="fa fa-arrow-circle-left"></i> Возврат на сайт 
                        </a>
                   </div>
                  </div>
               </div>   
          </nav>
  </header>

  <div id="dashboard">

    <div id="dashboard-nav" class="dashboard-nav">	
      {% block dashboard-nav %}
      {% endblock %}
    </div>

    <div class="dashboard-content">
      {% block dashboard-content %} 
      {% endblock %}
    </div>

  </div>

</div>

  {% block modal %}
  {% endblock %}
{% endblock %}

members/templates/members/change_password.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block dashboard-nav %}
  <ul>
    {% if request.user.is_company_admin %}
    <li><a href="{% url 'customers:dashboard' %}"><i class="fa fa-cogs"></i> Панель управления</a></li>
    {% endif %}
    <li><a href="{% url 'members:my_perks' %}"><i class="fa fa-gift"></i> Мои предложения</a></li>
    <li class="active"><a id="MLabel" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user-o"></i> Аккаунт</a>
      <ul class="dropdown-menu" aria-labelledby="MLabel">
        <li><a href="{% url 'members:edit_info' %}"><i class="fa fa-edit"></i> Редактировать</a></li>
        <li><a href="{% url 'members:change_password' %}"><i class="fa fa-key"></i> Сменить пароль</a></li>
      </ul>	
    </li>
    <li><a href="{% url 'members:logout' %}"><i class="fa fa-power-off"></i> Выйти</a></li>
  </ul>	
{% endblock %}
{% block dashboard-content %}
<div class="row">
  <div class="col-lg-6 col-md-8">
    <div class="add_listing_info">
      <form method="POST" action="" class="form-signin">
        {% csrf_token %}
        <h3>Сменить пароль</h3>
        {% if messages %}
          {% for message in messages %}
          <div class="alert alert-dismissable {{ message.tags }}">
            <strong>
            {{ message }}
            </strong>
          </div>
          {% endfor %}
        {% endif %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-block" value="Сохранить изменения">
      </form>
    </div>
  </div>
</div>
{% endblock %}

members/templates/members/edit_info.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block dashboard-nav %}
  <ul>
    {% if request.user.is_company_admin %}
    <li><a href="{% url 'customers:dashboard' %}"><i class="fa fa-cogs"></i> Панель управления</a></li>
    {% endif %}
    <li><a href="{% url 'members:my_perks' %}"><i class="fa fa-gift"></i> Мои предложения</a></li>
    <li class="active"><a id="MLabel" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user-o"></i> Аккаунт</a>
      <ul class="dropdown-menu" aria-labelledby="MLabel">
        <li><a href="{% url 'members:edit_info' %}"><i class="fa fa-edit"></i> Редактировать</a></li>
        <li><a href="{% url 'members:change_password' %}"><i class="fa fa-key"></i> Сменить пароль</a></li>
      </ul>	
    </li>
    <li><a href="{% url 'members:logout' %}"><i class="fa fa-power-off"></i> Выйти</a></li>
  </ul>	
{% endblock %}
{% block dashboard-content %}
<div class="row">
  <div class="col-lg-6 col-md-8">
    <div class="add_listing_info">
      <form method="POST" action="">
          {% csrf_token %}
        <h3>Редактировать информацию</h3>
          {% if messages %}
            {% for message in messages %}
            <div class="alert alert-dismissable {{ message.tags }}">
              <strong>
              {{ message }}
              </strong>
            </div>
            {% endfor %}
          {% endif %}
          {{ form|crispy }}
          <input type="submit" class="btn btn-block" value="Сохранить изменения">
      </form>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript">
$(document).ready(function(){
  $("#id_phone_number").inputmask("+7 (999) 999-9999",{ autoUnmask: true, removeMaskOnSubmit: true });
  $("#id_date_of_birth").inputmask("99.99.9999",{ "placeholder": "ДД.ММ.ГГГГ" });
});
</script>
{% endblock %}

members/templates/members/my_perks.html
{% extends 'dashboard.html' %}
{% load crispy_forms_tags %}

{% block dashboard-nav %}
<ul>
  {% if request.user.is_company_admin %}
  <li><a href="{% url 'customers:dashboard' %}"><i class="fa fa-cogs"></i> Панель управления</a></li>
  {% endif %}
  <li class="active"><a href="{% url 'members:my_perks' %}"><i class="fa fa-gift"></i> Мои предложения</a></li>
  <li><a id="MLabel" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user-o"></i> Аккаунт</a>
    <ul class="dropdown-menu" aria-labelledby="MLabel">
      <li><a href="{% url 'members:edit_info' %}"><i class="fa fa-edit"></i> Редактировать</a></li>
      <li><a href="{% url 'members:change_password' %}"><i class="fa fa-key"></i> Сменить пароль</a></li>
    </ul>	
  </li>
  <li><a href="{% url 'members:logout' %}"><i class="fa fa-power-off"></i> Выйти</a></li>
</ul>	
{% endblock %}
{% block dashboard-content %}
<div id="titlebar">
  <div class="row">
    <div class="col-md-12">
      <h2>Мои предложения</h2>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="dashboard-list-box">
      {% if transactions %}
      <h4>История получения предложений</h4>
      <ul>
        {% for t in transactions %}
        <li>
          <div class="list-box-listing">
            <div class="list-box-listing-img">
              <a href="{{ t.perk.get_absolute_url }}"><img src="{{ t.perk.thumbnail }}" alt="{{ t.perk.title }}"></a>
            </div>
            <div class="list-box-listing-content">
              <div class="inner">
                <h3><a href="{{ t.perk.get_absolute_url }}">{{ t.perk.title }}</a></h3>
                <span>{{ t.perk.short_description }}</span>
              </div>
              <div class="buttons-to-right">
                <span class="button gray">Код: {{ t.code }}</span>
                <span>{{ t.date_created }}</span>
              </div>
            </div>
          </div>
        </li>
        {% endfor %} 
      </ul> 
      {% else %}
      <h4>У вас пока нет полученных предложений</h4>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

members/templates/members/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section class="primary-bg">
	<div class="container">
    	<div id="login_signup">
            <div class="form_wrap_m">
            	<div class="white_box">
                	<h3>Регистрация</h3>
                  <div class="alert alert-dismissable alert-info">
                  Для завершения активации аккаунта Benefits, заполните небольшую форму:
                  </div>
                  {% if error %}
                  <div class="alert alert-dismissible alert-danger">
                    {{ error }}
                  </div>
                  {% endif %}
                  {% crispy form %}
              </div>
            </div>
      </div>
  </div>
</section>
{% endblock %}

{% block extra_js %}
<script type="text/javascript">
$(document).ready(function(){
  $("#id_phone_number").inputmask("+7 (999) 999-9999",{ autoUnmask: true, removeMaskOnSubmit: true });
  $("#id_date_of_birth").inputmask("99.99.9999",{ "placeholder": "ДД.ММ.ГГГГ" });
});
</script>
{% endblock %}

members/templates/members/registration_success.html
{% extends 'base.html' %}

{% block content %}
<section class="primary-bg">
	<div class="container">
    	<div id="login_signup">
            <div class="form_wrap_m">
            	<div class="white_box">
                	<h3>Добро пожаловать!</h3>
                  <div class="alert alert-dismissable alert-info">
                    Поздравляем! Вы успешно зарегистрированы в сервисе Benefits. Теперь у Вас появился доступ ко всем предложениям!
                  </div>
                  <a class="btn btn-block" href={% url 'perks:index' %}>
                    Начать работу с сервисом
                  </a>
              </div>
            </div>
      </div>
  </div>
</section>
{% endblock %}

members/templates/members/sign_in.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<section class="primary-bg">
	<div class="container">
    	<div id="login_signup">
            <div class="form_wrap_m">
            	<div class="white_box">
                	<h3>Вход в клуб Benefits</h3>
                  {% if error %}
                  <div class="alert alert-dismissible alert-danger">
                    {{ error }}
                  </div>
                  {% endif %}
                  {% crispy form %}
                    <p><a href="lost-password">Забыли пароль?</a></p>
                    <div class="back_home"><a href="{% url 'cms:index' %}" class="btn
                        outline-btn btn-sm"><i class="fa
                          fa-angle-double-left"></i>&nbsp;Вернуться на главную</a></div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}